// This file is auto-generated by Supabase and defines the database types
export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export interface Database {
  public: {
    Tables: {
      operations: {
        Row: {
          id: string
          operation_number: string
          amount: number
          currency: string
          exchange_rate: number
          service_rate: number
          equivalent_usd: number
          initial_company_share: number
          client_id: string | null
          mediator_id: string | null
          status: string
          date: string
          mediator_value: number | null
          final_company_share: number | null
          mediator_rate: number
          programmer_share: number
          investor_share: number
          is_profit_distributed?: boolean
          commission_type?: 'franc' | 'percentage' | null
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          operation_number: string
          amount: number
          currency: string
          exchange_rate: number
          service_rate: number
          equivalent_usd: number
          initial_company_share: number
          client_id?: string | null
          mediator_id?: string | null
          status: string
          date: string
          mediator_value?: number | null
          final_company_share?: number | null
          mediator_rate: number
          programmer_share: number
          investor_share: number
          is_profit_distributed?: boolean
          commission_type?: 'franc' | 'percentage' | null
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          operation_number?: string
          amount?: number
          currency?: string
          exchange_rate?: number
          service_rate?: number
          equivalent_usd?: number
          initial_company_share?: number
          client_id?: string | null
          mediator_id?: string | null
          status?: string
          date?: string
          mediator_value?: number | null
          final_company_share?: number | null
          mediator_rate?: number
          programmer_share?: number
          investor_share?: number
          is_profit_distributed?: boolean
          commission_type?: 'franc' | 'percentage' | null
          created_at?: string
          updated_at?: string
        }
      }
      individuals: {
        Row: {
          id: string
          name: string
          phone: string
          email: string
          type: string
          is_active: boolean
          mediator_type?: string
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          name: string
          phone: string
          email: string
          type: string
          is_active?: boolean
          mediator_type?: string
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          name?: string
          phone?: string
          email?: string
          type?: string
          is_active?: boolean
          mediator_type?: string
          created_at?: string
          updated_at?: string
        }
      }
      subscribers: {
        Row: {
          id: string
          individual_id: string
          subscription_amount: number
          status: string
          subscription_date: string
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          individual_id: string
          subscription_amount: number
          status?: string
          subscription_date: string
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          individual_id?: string
          subscription_amount?: number
          status?: string
          subscription_date?: string
          created_at?: string
          updated_at?: string
        }
      }
      mediator_percentage: {
        Row: {
          id: string
          mediator_id: string
          investor_id: string
          percentage: number
          status: 'active' | 'inactive'
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          mediator_id: string
          investor_id: string
          percentage: number
          status?: 'active' | 'inactive'
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          mediator_id?: string
          investor_id?: string
          percentage?: number
          status?: 'active' | 'inactive'
          created_at?: string
          updated_at?: string
        }
      }
      monthly_profits: {
        Row: {
          id: string
          individual_id: string
          share: number
          profit_date: string
          distribution_type?: string
          paid?: boolean | null
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          individual_id: string
          share: number
          profit_date: string
          distribution_type?: string
          paid?: boolean | null
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          individual_id?: string
          share?: number
          profit_date?: string
          distribution_type?: string
          paid?: boolean | null
          created_at?: string
          updated_at?: string
        }
      }
    }
    Views: {
      [_ in never]: never
    }
    Functions: {
      [_ in never]: never
    }
    Enums: {
      [_ in never]: never
    }
    CompositeTypes: {
      [_ in never]: never
    }
  }
}
